### ISSUE TITLE
Stats command conflicts with stats in mcMMO

### ISSUE THREAD

**Issue by madtomic** [kickash32/DistributedMobSpawns#9]
Can you change it or add another alias for stats? As if any server has mcMMO, stats command would not work.

**Comment by kickash32** [comment]
I'll need proof that it doesn't work for that to bother changing it or aliasing it. You also didn't give an alias suggestion.

**Comment by madtomic** [comment]
mcmmo uses mcstats and stats

we could use /dstats

**Comment by kickash32** [comment]
The command is /dms stats, I still don't see a conflict

**Comment by madtomic** [comment]
The resource spigot page said /stats?

**Comment by kickash32** [comment]
Ah I see the problem, ill fix the spigot page.
